[build]
  command = "npm install && npm run build"

[context.production.environment]
  NODE_ENV="production"
  VITE_API_BASE_URL="https://winelight-portal.onrender.com"

[context.deploy-preview.environment]
  NODE_ENV="production"
  VITE_API_BASE_URL="https://winelight-portal.onrender.com"

[context.branch-deploy.environment]
  NODE_ENV ="production"
  VITE_API_BASE_URL="https://winelight-portal.onrender.com"

